"""Generate material/UV variants of the bundled Kenney CC0 models.

Python 3 + Pillow. No downloads. --check verifies deterministic generated files.
The original models stay untouched; runtime only reads OBJ, MTL and PNG files.
"""
from collections import Counter
from io import BytesIO
from pathlib import Path
import argparse
import random

from PIL import Image

ROOT = Path(__file__).resolve().parents[1] / "App/Assets/Models/Title"
OUTPUT = ROOT / "Surface"


def texture(base, strength, seed, paving=False):
    """Low-contrast, periodic baked detail; no shader noise is required."""
    size = 256
    rng = random.Random(seed)
    grids = [(n, [rng.uniform(-1, 1) for _ in range(n * n)]) for n in (8, 24, 64)]

    def noise(u, v, n, grid):
        px, py = u * n, v * n
        ix, iy = int(px), int(py)
        fx, fy = px - ix, py - iy
        fx, fy = fx * fx * (3 - 2 * fx), fy * fy * (3 - 2 * fy)
        a = grid[(iy % n) * n + ix % n]
        b = grid[(iy % n) * n + (ix + 1) % n]
        c = grid[((iy + 1) % n) * n + ix % n]
        d = grid[((iy + 1) % n) * n + (ix + 1) % n]
        return (a + (b - a) * fx) * (1 - fy) + (c + (d - c) * fx) * fy

    pixels = []
    for y in range(size):
        for x in range(size):
            u, v = x / size, y / size
            variation = sum(weight * noise(u, v, n, grid)
                            for weight, (n, grid) in zip((0.25, 0.35, 0.4), grids))
            value = 1 + strength * variation
            if paving:
                edge = min(x, y, size - 1 - x, size - 1 - y)
                value *= 0.88 if edge < 2 else (0.96 if edge < 4 else 1)
            pixels.append(tuple(max(0, min(255, round(c * value))) for c in base))
    image = Image.new("RGB", (size, size))
    image.putdata(pixels)
    stream = BytesIO()
    image.save(stream, format="PNG")
    return stream.getvalue()


def text_bytes(text):
    return (text.rstrip() + "\n").replace("\r\n", "\n").replace("\n", "\r\n").encode("utf-8")


def derive(category, name, variant=None, scale=(4, 4, 4), tile=False):
    source = ROOT / category / (name + ".obj")
    lines = source.read_text(encoding="utf-8").splitlines()
    vertices = [list(map(float, line.split()[1:4])) for line in lines if line.startswith("v ")]
    normals = [list(map(float, line.split()[1:4])) for line in lines if line.startswith("vn ")]
    uvs = [list(map(float, line.split()[1:3])) for line in lines if line.startswith("vt ")]
    new_uvs, faces, counts = [], [], Counter()
    # Palette regions are authored choices for these specific Kenney source files.
    # No material classification occurs in the renderer or shader.
    for line in lines:
        if not line.startswith("f "):
            continue
        corners = [tuple(map(int, corner.split("/"))) for corner in line.split()[1:]]
        assert len(corners) == 3 and all(min(c) > 0 for c in corners)
        face_uvs = [uvs[t - 1] for _, t, _ in corners]
        material = "palette"
        if tile:
            material = "paving" if variant == "sidewalk" else "concrete"
        elif category == "Commercial" and all(
            abs(u - 0.46875) < 0.00001 and 0.25 <= v <= 0.5 for u, v in face_uvs
        ):
            material = "plaster"
        elif category == "Roads" and all(
            abs(u - 0.03125) < 0.00001 and abs(v - 0.125) < 0.00001 for u, v in face_uvs
        ):
            material = "asphalt_edge"
        elif category == "Roads" and all(
            abs(u - 0.28125) < 0.00001 and abs(v - 0.125) < 0.00001 for u, v in face_uvs
        ):
            material = "asphalt"
        if material != "palette":
            normal = normals[corners[0][2] - 1]
            axis = max(range(3), key=lambda i: abs(normal[i]))
            axes = ((2, 1), (0, 2), (0, 1))[axis]
            repeat = 0.8 if material == "paving" else 2.0
            changed = []
            for vertex, _, normal_index in corners:
                p = vertices[vertex - 1]
                new_uvs.append(tuple(p[i] * scale[i] / repeat for i in axes))
                changed.append((vertex, len(uvs) + len(new_uvs), normal_index))
            corners = changed
        faces.append((material, corners))
        counts[material] += 1
    assert counts["paving" if variant == "sidewalk" else
                  "concrete" if tile else "plaster" if category == "Commercial" else "asphalt"] > 0
    target = variant or name
    output = ["# Derived from Kenney CC0. Generated by scripts/GenerateTitleMaterials.py.",
              f"mtllib {target}.mtl"]
    # Preserve vertex positions, vertex colors and normals verbatim.
    output += [line for line in lines if line.startswith(("v ", "vn ", "vt "))]
    output += [f"vt {u:.8f} {v:.8f}" for u, v in new_uvs]
    previous = None
    for material, corners in faces:
        if material != previous:
            output.append("usemtl " + material)
            previous = material
        output.append("f " + " ".join("/".join(map(str, c)) for c in corners))
    mtl = ["# Kenney CC0 geometry; project-generated surface textures."]
    for material in sorted(counts):
        texture_path = (f"../../{category}/Textures/colormap.png" if material == "palette"
                        else f"../Textures/{'asphalt' if material == 'asphalt_edge' else material}.png")
        diffuse = "Kd 0.794118 0.794393 0.796875" if material == "asphalt_edge" else "Kd 1 1 1"
        mtl += [f"newmtl {material}", diffuse, f"map_Kd {texture_path}", ""]
    return {f"{category}/{target}.obj": text_bytes("\n".join(output)),
            f"{category}/{target}.mtl": text_bytes("\n".join(mtl))}, counts


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = {}
    for name, base, strength, seed in [
        ("asphalt", (102, 107, 128), 0.28, 10),
        ("plaster", (232, 232, 240), 0.09, 20),
        ("concrete", (160, 168, 201), 0.12, 30),
        ("paving", (160, 168, 201), 0.10, 40),
    ]:
        files[f"Textures/{name}.png"] = texture(base, strength, seed, name == "paving")
    models = [("Commercial", name, None, (4, 4, 4), False) for name in
              ("building-c", "building-e", "building-h", "building-k",
               "building-skyscraper-a", "building-skyscraper-e")]
    models += [("Roads", "road-straight", None, (4, 4, 4), False),
               ("Roads", "tile-low", "sidewalk", (1.6, 4, 4), True),
               ("Roads", "tile-low", "ground", (160, 4, 180), True)]
    for model in models:
        generated, counts = derive(*model)
        files.update(generated)
        print(model[2] or model[1], dict(counts))
    for relative, data in files.items():
        path = OUTPUT / relative
        if args.check:
            if not path.is_file() or path.read_bytes() != data:
                raise SystemExit(f"Generated asset mismatch: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    print(f"{'Verified' if args.check else 'Generated'} {len(files)} assets")


if __name__ == "__main__":
    main()
